# Generated by Django 4.2.27 on 2026-07-07 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('framework', models.CharField(choices=[('react', 'React.js'), ('nextjs', 'Next.js'), ('vue', 'Vue.js'), ('nuxt', 'Nuxt.js'), ('angular', 'Angular'), ('svelte', 'Svelte'), ('other', 'Other')], default='nextjs', max_length=50)),
                ('environment', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('development', 'Development'), ('preview', 'Preview')], default='production', max_length=50)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('scan_mobile', models.BooleanField(default=True)),
                ('scan_desktop', models.BooleanField(default=True)),
                ('deployment_version', models.CharField(blank=True, max_length=100)),
                ('git_commit_id', models.CharField(blank=True, max_length=100)),
                ('build_time', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'owner')},
            },
        ),
    ]
