# Generated by Django 4.2.27 on 2026-07-07 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_api_key', models.CharField(blank=True, max_length=500)),
                ('scan_interval_hours', models.PositiveIntegerField(default=6)),
                ('alert_performance_threshold', models.FloatField(default=80)),
                ('alert_lcp_threshold', models.FloatField(default=2500)),
                ('alert_cls_threshold', models.FloatField(default=0.1)),
                ('alert_inp_threshold', models.FloatField(default=200)),
                ('email_alerts_enabled', models.BooleanField(default=True)),
                ('slack_alerts_enabled', models.BooleanField(default=False)),
                ('slack_webhook_url', models.URLField(blank=True)),
                ('email_recipients', models.TextField(blank=True, help_text='Comma-separated emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Null = global settings', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App Settings',
                'verbose_name_plural': 'App Settings',
            },
        ),
    ]
