# Generated by Django 4.2.27 on 2026-07-24 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredWebsite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=2048)),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('tcp', 'TCP'), ('ping', 'PING')], default='https', max_length=10)),
                ('check_interval', models.IntegerField(choices=[(1, 'Every 1 minute'), (5, 'Every 5 minutes'), (10, 'Every 10 minutes'), (30, 'Every 30 minutes'), (60, 'Every 1 hour')], default=5)),
                ('active', models.BooleanField(default=True)),
                ('ssl_monitoring', models.BooleanField(default=True)),
                ('ssl_expiry_alert_days', models.IntegerField(default=30)),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('expected_status_code', models.IntegerField(default=200)),
                ('keyword_check', models.CharField(blank=True, help_text='Check that this keyword appears in the response', max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_websites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monitored Website',
                'verbose_name_plural': 'Monitored Websites',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SSLCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cert_status', models.CharField(choices=[('healthy', 'Healthy'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('invalid', 'Invalid'), ('hostname_mismatch', 'Hostname Mismatch'), ('handshake_failed', 'Handshake Failed'), ('disabled', 'SSL Disabled')], max_length=20)),
                ('issuer', models.CharField(blank=True, max_length=500)),
                ('common_name', models.CharField(blank=True, max_length=500)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('days_remaining', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_checks', to='uptime.monitoredwebsite')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='SSLAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('invalid', 'Invalid Certificate'), ('hostname_mismatch', 'Hostname Mismatch'), ('handshake_failed', 'SSL Handshake Failed')], max_length=25)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('days_remaining', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=15)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('ssl_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uptime.sslcheck')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_alerts', to='uptime.monitoredwebsite')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('provider_type', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('webhook', 'Generic Webhook')], max_length=15)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict, help_text='Provider-specific configuration (webhook_url, bot_token, chat_id, etc.)')),
                ('notify_on_down', models.BooleanField(default=True)),
                ('notify_on_recovery', models.BooleanField(default=True)),
                ('notify_on_ssl_expiring', models.BooleanField(default=True)),
                ('notify_on_ssl_expired', models.BooleanField(default=True)),
                ('notify_on_ssl_invalid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('timeout', 'Timeout'), ('error', 'Error')], max_length=10)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='uptime.monitoredwebsite')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='uptime.monitoredwebsite')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sslcheck',
            index=models.Index(fields=['website', '-checked_at'], name='uptime_sslc_website_a4d816_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringcheck',
            index=models.Index(fields=['website', '-checked_at'], name='uptime_moni_website_6257df_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringcheck',
            index=models.Index(fields=['website', 'status'], name='uptime_moni_website_4f17e7_idx'),
        ),
    ]
