# Generated by Django 4.2.27 on 2026-07-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredwebsite',
            name='verify_ssl',
            field=models.BooleanField(default=True, help_text='Verify SSL certificate chain. Disable for self-signed certificates.'),
        ),
    ]
