# Generated by Django 4.2.27 on 2026-07-07 12:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performance_score', models.FloatField(default=0)),
                ('accessibility_score', models.FloatField(default=0)),
                ('seo_score', models.FloatField(default=0)),
                ('best_practices_score', models.FloatField(default=0)),
                ('lcp', models.FloatField(blank=True, help_text='Largest Contentful Paint (ms)', null=True)),
                ('cls', models.FloatField(blank=True, help_text='Cumulative Layout Shift', null=True)),
                ('inp', models.FloatField(blank=True, help_text='Interaction to Next Paint (ms)', null=True)),
                ('fcp', models.FloatField(blank=True, help_text='First Contentful Paint (ms)', null=True)),
                ('ttfb', models.FloatField(blank=True, help_text='Time to First Byte (ms)', null=True)),
                ('speed_index', models.FloatField(blank=True, help_text='Speed Index (ms)', null=True)),
                ('total_blocking_time', models.FloatField(blank=True, help_text='Total Blocking Time (ms)', null=True)),
                ('strategy', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], default='mobile', max_length=10)),
                ('bundle_size', models.FloatField(blank=True, help_text='Bundle size in KB', null=True)),
                ('largest_js_bundle', models.FloatField(blank=True, help_text='Largest JS bundle in KB', null=True)),
                ('image_optimization_score', models.FloatField(blank=True, null=True)),
                ('unused_javascript', models.FloatField(blank=True, help_text='Unused JS in KB', null=True)),
                ('unused_css', models.FloatField(blank=True, help_text='Unused CSS in KB', null=True)),
                ('compression_enabled', models.BooleanField(blank=True, null=True)),
                ('caching_enabled', models.BooleanField(blank=True, null=True)),
                ('cdn_detected', models.BooleanField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project')),
            ],
            options={
                'verbose_name': 'Performance Report',
                'verbose_name_plural': 'Performance Reports',
                'ordering': ['-tested_at'],
                'indexes': [models.Index(fields=['project', '-tested_at'], name='reports_per_project_f48e4c_idx'), models.Index(fields=['strategy'], name='reports_per_strateg_56b70b_idx'), models.Index(fields=['-tested_at'], name='reports_per_tested__633666_idx')],
            },
        ),
    ]
