# Generated by Django 4.2.27 on 2026-07-23 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RumApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('api_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('environment', models.CharField(default='production', max_length=50)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('allowed_origins', models.TextField(blank=True, help_text='Comma-separated allowed origins')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rum_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RumSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=255)),
                ('anonymous_id', models.CharField(blank=True, max_length=100)),
                ('browser_name', models.CharField(blank=True, max_length=100)),
                ('browser_version', models.CharField(blank=True, max_length=50)),
                ('os_name', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('screen_resolution', models.CharField(blank=True, max_length=20)),
                ('network_type', models.CharField(blank=True, max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='rum.rumapplication')),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('application', 'session_id')},
            },
        ),
        migrations.CreateModel(
            name='RumEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_url', models.TextField()),
                ('api_name', models.CharField(blank=True, max_length=500)),
                ('method', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post'), ('PUT', 'Put'), ('PATCH', 'Patch'), ('DELETE', 'Delete'), ('OPTIONS', 'Options'), ('HEAD', 'Head')], default='GET', max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('request_headers', models.JSONField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, null=True)),
                ('start_time', models.FloatField(blank=True, null=True)),
                ('end_time', models.FloatField(blank=True, null=True)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('dns_time_ms', models.FloatField(blank=True, null=True)),
                ('tcp_time_ms', models.FloatField(blank=True, null=True)),
                ('tls_time_ms', models.FloatField(blank=True, null=True)),
                ('ttfb_ms', models.FloatField(blank=True, null=True)),
                ('download_time_ms', models.FloatField(blank=True, null=True)),
                ('page_url', models.TextField(blank=True)),
                ('previous_url', models.TextField(blank=True)),
                ('route_name', models.CharField(blank=True, max_length=500)),
                ('referrer', models.TextField(blank=True)),
                ('environment', models.CharField(blank=True, max_length=50)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rum.rumapplication')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='rum.rumsession')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['application', 'timestamp'], name='rum_rumeven_applica_f4ecc2_idx'), models.Index(fields=['application', 'success'], name='rum_rumeven_applica_60c735_idx'), models.Index(fields=['application', 'status_code'], name='rum_rumeven_applica_8113b3_idx'), models.Index(fields=['api_url'], name='rum_rumeven_api_url_c3de2d_idx')],
            },
        ),
    ]
